# **Proyecto Integrador (Hito 1): Construcción del Dataset Analítico**
 ## Grupo 9

**Integrantes:**
* Nahuel Ezequiel Gomez
* Priscilla Oriana Flores
* Santiago Armanino
* Mariangel Mariela Faro Machado

----

## **¿Qué tipo de análisis permitirá tu dataset en el siguiente módulo?**

Observar las tendencias de los clientes y su segmentacion sobre su localizacion, rentabilidad, preferencia de productos, categorias y marcas.
Cada registro corresponde a la compra individual de un producto.

----

## **¿Qué tablas decidiste utilizar y por qué?**

Las tablas utilizadas fueron: `Clientes`, `Productos`, `Geografia`,`Clientes_Ubicacion`,`Pedidos`.

Nuestro objetivo es analizar el comportamiento y tendencias de cada `Segmentacion` de la `Tabla Clientes`, relacionado a su ubicacion y los productos que compran.

----

## **¿Qué columnas seleccionaste y cuáles descartaste?**

#### **Columnas Descartadas:**

`ID_Campania`,`ID_Producto`,`Codigo_Barra`,`Codigo_Interno`,`ID_Ubicacion`,`ID_Detalle`:
Son variables de referencia y llaves una vez limpiado en dataframe no tienen valor para el analisis.

--

`Precio_Lista`,`Costo_Unitario`,`Descuento`,`Fecha_Envio`,`Zona_Logistica`,`Activo`, `Detalle_Pedido`:
Son variables irrelevantes para nuestro analisis enfocado observar el comportamiento y tendencias de los clientes.

--

`Pais`,`Tipo_Direccion`:
Todo el registro indica que son solo las sucursales de Chile, asi como solo estan registrado los tipo de direccion principales.

--

`Codigo_Postal`,`Latitud_Ref`:
Una direccion demasiado especifica no es requerida para este tipo de analisis.



#### **Columnas Seleccionadas:**
`ID_Cliente`,`Nombre_Cliente`,`Fecha_Registro`,`Antiguedad_Dias`,`Segmento`,
`Puntaje_Fidelidad`,`Canal_Preferido`y  `Fecha_Actualizacion`: Casi todos de la columna de la tabla `Clientes`, nuestro principal foco de analisis sobre su comportamiento. Con `Antiguedad_Dias` nuestra variable calculada. Y con `ID_Clientes` permitiendonos calcular la cantidad de Clientes registrados.

--

`Region`,`Estado`,`Ciudad`: Columnas de las tabla de `Geografia` utilizando `Clientes_Ubicacion` como intermedio para obtener la ubicacion aproximada de los Clientes.

--

`ID_Pedido`,`Fecha_Pedido`,`Modo_Envio`,`Prioridad`,`Estado_Pedido`, `Etiqueta_Ventas` y `Etiqueta_Ganancia`,`Ventas`,`Ganancia`,`Margen_Rentabilidad_%`: Columnas de la tabla `Pedido`, utilizado para evaluar tendencias y rentabilidad de los clientes y segmentacion. Siendo `Margen_Rentabilidad_%` nuestra otra variable calculada. Y con `ID_Pedido` permitiendonos calcular la cantidad de pedidos realizados.

--

`Nombre_Producto`,`Categoria`,`Subcategoria`,`Marca`,`Cantidad`: Columnas de la tabla `Productos` habiendo utilizado de intermedio la tabla `Detalle_Pedido`, utilizado para evaluar tendencias y preferencias de los clientes respecto a los productos, categorias y marcas mas pedidos, asi como cuales son los segmentos que mas cantidades compran.

##Montaje del entorno

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')
"""
Esto es para usar tu cuenta de drive, esto es personal para cada uno por lo que
no se expondra informacion personal. Deberas darle permisos a Colab para acceder
a tu google drive

Para que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu
drive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro
el archivo de 34_SuperTienda_Espanol.db

Mas abajo dejare una opcion para ejecutarlo sin el drive.
"""

'\nEsto es para usar tu cuenta de drive, esto es personal para cada uno por lo que\nno se expondra informacion personal. Deberas darle permisos a Colab para acceder\na tu google drive\n\nPara que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu\ndrive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro\nel archivo de 34_SuperTienda_Espanol.db\n\nMas abajo dejare una opcion para ejecutarlo sin el drive.\n'

In [ ]:
#Setting de sql y pandas
import sqlite3
import pandas as pd

%load_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

"""
Dependiendo de la opcion que uses, deberas comentar una opcion u otra para
evitar generar errores y luego cambiarlo en conn = sqlite3.connect(opcion_Elegida)
"""

#Ruta del archivo guardada en drive
#ruta_drive = '/content/drive/MyDrive/Hitos_Skillnest/Hito1/34_SuperTienda_Espanol.db'

#Ruta del archivo subida al entorno, debes subirlo a la raiz del entorno de ejecucion.
ruta = '/content/34_SuperTienda_Espanol.db'

"""
-----------------------------------------------
"""

#Cambiar la variable de ruta segun si estas usando el drive o el archivo subido
#al entorno de ejecucion
conn = sqlite3.connect(ruta) #Se realiza la conexion con la base de datos


#Guardamos la consulta SQL como string, en este caso es para poder conseguir
# el nombre de las tablas presentes en la base de datos.
query = "SELECT name FROM sqlite_master WHERE type='table';"

#ejecutamos la consulta en la base de datos
df_tables =  pd.read_sql_query(query, conn)

print(df_tables) # :D tablas

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
                name
0           Clientes
1          Productos
2          Geografia
3  Cliente_Ubicacion
4          Campanias
5            Pedidos
6     Detalle_Pedido
7            Soporte

In [ ]:
#Setting de los Dataframes

df_clientes = pd.read_sql("SELECT * FROM Clientes", conn)

df_productos = pd.read_sql("SELECT * FROM Productos", conn)

df_geografia = pd.read_sql("SELECT * FROM Geografia", conn)

df_cli_ubicacion = pd.read_sql("SELECT * FROM Cliente_Ubicacion", conn)

df_pedidos = pd.read_sql("SELECT * FROM Pedidos", conn)

df_det_pedidos = pd.read_sql("SELECT * FROM Detalle_Pedido", conn)

## Limpieza de Tablas

### Tabla Clientes

#### Chequeo Preliminar - Tabla Clientes

In [ ]:
df_clientes

,ID_Cliente,Nombre_Cliente,Segmento,Fecha_Registro,Canal_Preferido,Puntaje_Fidelidad,Codigo_Interno
0,C0001,Fernanda Díaz,Consumidor,2023-02-18,Web,55,CLI-6635-Z
1,C0002,Valentina Muñoz,Home Office,2023-07-30,Web,58,CLI-2291-Z
2,C0003,Diego Castillo,Corporativo,2024-03-28,App,100,CLI-2139-X
3,C0004,Nicolás Silva,Corporativo,2021-06-13,App,22,CLI-7227-Y
4,C0005,Daniela Rodríguez,Consumidor,2023-01-29,Teléfono,36,CLI-5374-Z
...,...,...,...,...,...,...,...
295,C0296,Catalina Muñoz,Consumidor,2024-08-28,App,78,CLI-1611-X
296,C0297,Sebastián Soto,Consumidor,2023-03-25,Correo,33,CLI-5742-X
297,C0298,Ana Sepúlveda,Home Office,2024-05-19,Web,52,CLI-5662-Y
298,C0299,Catalina Flores,Home Office,2023-10-09,App,74,CLI-8668-Y
299,C0300,Camila Díaz,Corporativo,2021-11-29,Correo,92,CLI-5215-Z

In [ ]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_Cliente         300 non-null    object
 1   Nombre_Cliente     300 non-null    object
 2   Segmento           300 non-null    object
 3   Fecha_Registro     300 non-null    object
 4   Canal_Preferido    283 non-null    object
 5   Puntaje_Fidelidad  300 non-null    int64
 6   Codigo_Interno     300 non-null    object
dtypes: int64(1), object(6)
memory usage: 16.5+ KB

In [ ]:

df_clientes.isnull().sum()

ID_Cliente            0
Nombre_Cliente        0
Segmento              0
Fecha_Registro        0
Canal_Preferido      17
Puntaje_Fidelidad     0
Codigo_Interno        0
dtype: int64

#### Limpieza de tabla Clientes

In [ ]:
# Verificación y conversión de tipos de datos
df_clientes['Fecha_Registro'] = pd.to_datetime(df_clientes['Fecha_Registro'])
df_clientes['Fecha_Registro'].dt.tz_localize(None)

# Tratamiento de Valores Nulos
# Reemplazamos los canales preferidos faltantes por 'No Especificado'
df_clientes['Canal_Preferido'] = df_clientes['Canal_Preferido'].fillna('No Especificado')

# Limpiar espacios en blanco
columnas_texto = ["Nombre_Cliente","Segmento","Canal_Preferido"]
for col in columnas_texto:
    df_clientes[col] = df_clientes[col].str.strip()

# Formato consistente
df_clientes["Canal_Preferido"] = df_clientes["Canal_Preferido"].str.title()

# Variable tiempo
fecha_actual = pd.Timestamp.today()

df_clientes["Antiguedad_Dias"] = (
    fecha_actual - df_clientes["Fecha_Registro"]
).dt.days

# Verificación final
print(df_clientes.isnull().sum())
print(df_clientes.duplicated().sum())

df_clientes.head()

ID_Cliente           0
Nombre_Cliente       0
Segmento             0
Fecha_Registro       0
Canal_Preferido      0
Puntaje_Fidelidad    0
Codigo_Interno       0
Antiguedad_Dias      0
dtype: int64
0

,ID_Cliente,Nombre_Cliente,Segmento,Fecha_Registro,Canal_Preferido,Puntaje_Fidelidad,Codigo_Interno,Antiguedad_Dias
0,C0001,Fernanda Díaz,Consumidor,2023-02-18,Web,55,CLI-6635-Z,1257
1,C0002,Valentina Muñoz,Home Office,2023-07-30,Web,58,CLI-2291-Z,1095
2,C0003,Diego Castillo,Corporativo,2024-03-28,App,100,CLI-2139-X,853
3,C0004,Nicolás Silva,Corporativo,2021-06-13,App,22,CLI-7227-Y,1872
4,C0005,Daniela Rodríguez,Consumidor,2023-01-29,Teléfono,36,CLI-5374-Z,1277

### Tabla Clientes ubicacion

#### Chequeo Preliminar - Clientes Ubicacion

In [ ]:
df_cli_ubicacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           300 non-null    object
 1   ID_Ubicacion         300 non-null    object
 2   Tipo_Direccion       300 non-null    object
 3   Fecha_Actualizacion  300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [ ]:
df_cli_ubicacion.describe(include='all')

       ID_Cliente ID_Ubicacion Tipo_Direccion Fecha_Actualizacion
count         300          300            300                 300
unique        300           13              1                 220
top         C0300        UB007      Principal          2024-12-26
freq            1           33            300                   4

#### Limpieza - Chequeo Ubicacion

In [ ]:
#Solo se necesita transformar el tipo de variable de object a datetime
df_cli_ubicacion['Fecha_Actualizacion'] = pd.to_datetime(df_cli_ubicacion['Fecha_Actualizacion'])
df_cli_ubicacion['Fecha_Actualizacion'] = df_cli_ubicacion['Fecha_Actualizacion'].dt.tz_localize(None)

# Chequeo final
df_cli_ubicacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           300 non-null    object
 1   ID_Ubicacion         300 non-null    object
 2   Tipo_Direccion       300 non-null    object
 3   Fecha_Actualizacion  300 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 9.5+ KB

### Tabla Geografia

#### Chequeo Preliminar - Geografia

In [ ]:
df_geografia.head(5)

,ID_Ubicacion,Pais,Region,Estado,Ciudad,Codigo_Postal,Zona_Logistica,Latitud_Ref
0,UB001,Chile,Norte,Antofagasta,Antofagasta,1240000,A,-52.1246
1,UB002,Chile,Norte,Coquimbo,La Serena,1700000,C,-44.4288
2,UB003,Chile,Norte,Tarapacá,Iquique,1100000,B,-27.2235
3,UB004,Chile,Centro,Metropolitana,Santiago,8320000,A,-32.3328
4,UB005,Chile,Centro,Valparaíso,Valparaíso,2340000,A,-51.9571

In [ ]:
df_geografia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Ubicacion    13 non-null     object
 1   Pais            13 non-null     object
 2   Region          13 non-null     object
 3   Estado          13 non-null     object
 4   Ciudad          13 non-null     object
 5   Codigo_Postal   13 non-null     object
 6   Zona_Logistica  13 non-null     object
 7   Latitud_Ref     13 non-null     float64
dtypes: float64(1), object(7)
memory usage: 964.0+ bytes

In [ ]:
df_geografia.describe(include= 'all')

,ID_Ubicacion,Pais,Region,Estado,Ciudad,Codigo_Postal,Zona_Logistica,Latitud_Ref
count,13,13,13,13,13,13,13,13.000000
unique,13,1,4,13,13,13,4,NaN
top,UB001,Chile,Centro,Antofagasta,Antofagasta,1240000,A,NaN
freq,1,13,4,1,1,1,5,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-36.462569
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.974471
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-52.124600
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-44.856900
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-33.356400
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-27.223500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-19.497500

In [ ]:
string_column = ["Pais","Region","Estado", "Ciudad", "Zona_Logistica"]
for col in string_column:
    df_geografia[col] = df_geografia[col].str.strip()

print("Value Counts para detectar categoria adicionales y errores gramaticales")
print('---------------------------------')
print(df_geografia['Pais'].value_counts())
print('---------------------------------')

print('')
print('---------------------------------')
print(df_geografia['Region'].value_counts())
print('---------------------------------')
print('')
print('---------------------------------')
print(df_geografia['Estado'].value_counts())
print('---------------------------------')

print('')
print('---------------------------------')
print(df_geografia['Zona_Logistica'].value_counts())
print('---------------------------------')

Value Counts para detectar categoria adicionales y errores gramaticales
---------------------------------
Pais
Chile    13
Name: count, dtype: int64
---------------------------------

---------------------------------
Region
Centro     4
Sur        4
Norte      3
Austral    2
Name: count, dtype: int64
---------------------------------

---------------------------------
Estado
Antofagasta      1
Coquimbo         1
Tarapacá         1
Metropolitana    1
Valparaíso       1
O'Higgins        1
Maule            1
Biobío           1
La Araucanía     1
Los Lagos        1
Los Ríos         1
Aysén            1
Magallanes       1
Name: count, dtype: int64
---------------------------------

---------------------------------
Zona_Logistica
A    5
B    4
C    3
D    1
Name: count, dtype: int64
---------------------------------

### Tabla Pedidos

#### Chequeo Preliminar - Pedidos

In [ ]:
df_pedidos.head()

,ID_Pedido,ID_Cliente,Fecha_Pedido,Fecha_Envio,Modo_Envio,ID_Campania,Estado_Pedido,Observacion_Interna
0,ORD-2023-00001,C0174,2025-03-31,2025-04-04,Estándar,None,Completado,Cliente frecuente
1,ORD-2023-00002,C0254,2024-03-25,2024-03-25,Segunda Clase,MKT005,Completado,Sin observaciones
2,ORD-2023-00003,C0203,2024-02-20,2024-02-24,Estándar,MKT001,Completado,Revisar descuento aplicado
3,ORD-2023-00004,C0258,2023-10-29,2023-10-31,Primera Clase,None,Enviado,Sin observaciones
4,ORD-2023-00005,C0118,2025-03-30,2025-04-01,Estándar,MKT006,Completado,Verificar dirección

In [ ]:
df_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Pedido            1200 non-null   object
 1   ID_Cliente           1200 non-null   object
 2   Fecha_Pedido         1200 non-null   object
 3   Fecha_Envio          1200 non-null   object
 4   Modo_Envio           1200 non-null   object
 5   ID_Campania          516 non-null    object
 6   Estado_Pedido        1200 non-null   object
 7   Observacion_Interna  1200 non-null   object
dtypes: object(8)
memory usage: 75.1+ KB

In [ ]:
df_pedidos.describe(include = 'all')

,ID_Pedido,ID_Cliente,Fecha_Pedido,Fecha_Envio,Modo_Envio,ID_Campania,Estado_Pedido,Observacion_Interna
count,1200,1200,1200,1200,1200,516,1200,1200
unique,1200,289,646,644,4,8,4,7
top,ORD-2025-01184,C0120,2023-05-11,2024-06-25,Estándar,MKT003,Completado,Revisar descuento aplicado
freq,1,12,6,7,311,72,879,199

In [ ]:
print("Value Counts para detectar categoria adicionales y errores gramaticales")
print('')
print('---------------------------------')
print(df_pedidos['Estado_Pedido'].value_counts())
print('---------------------------------')
print('')
print('')
print('---------------------------------')
print(df_pedidos['Modo_Envio'].value_counts())
print('---------------------------------')
print('')
print('---------------------------------')
print(df_pedidos['Observacion_Interna'].value_counts())
print('---------------------------------')

Value Counts para detectar categoria adicionales y errores gramaticales

---------------------------------
Estado_Pedido
Completado    879
Enviado       207
Cancelado      65
Devuelto       49
Name: count, dtype: int64
---------------------------------


---------------------------------
Modo_Envio
Estándar         311
Primera Clase    310
Segunda Clase    294
Mismo Día        285
Name: count, dtype: int64
---------------------------------

---------------------------------
Observacion_Interna
Revisar descuento aplicado    199
Cliente frecuente             180
Sin observaciones             171
Entrega parcial               169
Verificar dirección           165
Posible recompra              161
Escalado por soporte          155
Name: count, dtype: int64
---------------------------------

#### Limpieza - Pedidos

In [ ]:
df_pedidos['ID_Campania'] = df_pedidos['ID_Campania'].fillna('Sin Registro')

df_pedidos['Fecha_Pedido'] = pd.to_datetime(df_pedidos['Fecha_Pedido'])
df_pedidos['Fecha_Envio'] = pd.to_datetime(df_pedidos['Fecha_Envio'])


df_pedidos['Fecha_Pedido'] = df_pedidos['Fecha_Pedido'].dt.tz_localize(None)
df_pedidos['Fecha_Envio'] = df_pedidos['Fecha_Envio'].dt.tz_localize(None)

df_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Pedido            1200 non-null   object
 1   ID_Cliente           1200 non-null   object
 2   Fecha_Pedido         1200 non-null   datetime64[ns]
 3   Fecha_Envio          1200 non-null   datetime64[ns]
 4   Modo_Envio           1200 non-null   object
 5   ID_Campania          1200 non-null   object
 6   Estado_Pedido        1200 non-null   object
 7   Observacion_Interna  1200 non-null   object
dtypes: datetime64[ns](2), object(6)
memory usage: 75.1+ KB

### Tabla detalle pedidos

In [ ]:
print("--- 1. ANÁLISIS DE DATOS NULOS O FALTANTES ---")
print(df_det_pedidos.isnull().sum())

print("\n--- 2. DISTRIBUCIÓN DE VOLUMEN (CANTIDADES) ---")
print(df_det_pedidos['Cantidad'].value_counts().sort_index())

--- 1. ANÁLISIS DE DATOS NULOS O FALTANTES ---
ID_Detalle     0
ID_Pedido      0
ID_Producto    0
Cantidad       0
Descuento      0
Ventas         0
Ganancia       0
Prioridad      0
dtype: int64

--- 2. DISTRIBUCIÓN DE VOLUMEN (CANTIDADES) ---
Cantidad
1    374
2    365
3    417
4    381
5    383
6    362
7    370
8    374
Name: count, dtype: int64

In [ ]:
# 1. Calcular IQR para Ganancias y Ventas
Q1_g = df_det_pedidos['Ganancia'].quantile(0.25)
Q3_g = df_det_pedidos['Ganancia'].quantile(0.75)
IQR_g = Q3_g - Q1_g
limite_inf_g = Q1_g - 1.5 * IQR_g
limite_sup_g = Q3_g + 1.5 * IQR_g

Q3_v = df_det_pedidos['Ventas'].quantile(0.75)
limite_sup_v = Q3_v + 1.5 * (Q3_v - df_det_pedidos['Ventas'].quantile(0.25))

# 2. Crear las variables calculadas por defecto
df_det_pedidos['Etiqueta_Ganancia'] = 'Normal'
df_det_pedidos['Etiqueta_Ventas'] = 'Normal'

# 3. Aplicar las etiquetas a los outliers detectados sean positivos o negativos.
df_det_pedidos.loc[df_det_pedidos['Ganancia'] > limite_sup_g, 'Etiqueta_Ganancia'] = 'Ganancia Atípica'
df_det_pedidos.loc[df_det_pedidos['Ganancia'] < limite_inf_g, 'Etiqueta_Ganancia'] = 'Pérdida Crítica'
df_det_pedidos.loc[df_det_pedidos['Ventas'] > limite_sup_v, 'Etiqueta_Ventas'] = 'Venta Extraordinaria'

print("Variables calculadas agregadas exitosamente.")

Variables calculadas agregadas exitosamente.

In [ ]:
# 4. Verificación de duplicados
print(df_det_pedidos.duplicated().sum())

0

In [ ]:
# 5. Buscar por si hay IDs fantasmas cruzando con las tablas maestras
pedidos_fantasma = df_det_pedidos[~df_det_pedidos['ID_Pedido'].isin(df_pedidos['ID_Pedido'])]
productos_fantasma = df_det_pedidos[~df_det_pedidos['ID_Producto'].isin(df_productos['ID_Producto'])]

print("--- RESULTADOS DE LA VALIDACIÓN DE INTEGRIDAD ---")
print(f"Fallas en Pedidos: {len(pedidos_fantasma)} registros huérfanos.")
print(f"Fallas en Productos: {len(productos_fantasma)} registros huérfanos.")

--- RESULTADOS DE LA VALIDACIÓN DE INTEGRIDAD ---
Fallas en Pedidos: 0 registros huérfanos.
Fallas en Productos: 0 registros huérfanos.

In [ ]:
# Creación de métrica financiera, variable calculada numérica.
df_det_pedidos['Margen_Rentabilidad_%'] = round((df_det_pedidos['Ganancia'] / df_det_pedidos['Ventas']) * 100, 2)

In [ ]:
df_det_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3026 entries, 0 to 3025
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_Detalle             3026 non-null   int64
 1   ID_Pedido              3026 non-null   object
 2   ID_Producto            3026 non-null   object
 3   Cantidad               3026 non-null   int64
 4   Descuento              3026 non-null   float64
 5   Ventas                 3026 non-null   float64
 6   Ganancia               3026 non-null   float64
 7   Prioridad              3026 non-null   object
 8   Etiqueta_Ganancia      3026 non-null   object
 9   Etiqueta_Ventas        3026 non-null   object
 10  Margen_Rentabilidad_%  3026 non-null   float64
dtypes: float64(4), int64(2), object(5)
memory usage: 260.2+ KB

### Tabla Productos

#### Chequeo Preliminar - Productos

In [ ]:
#estadisticas de tabla "Productos"
df_productos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Producto      120 non-null    object
 1   Nombre_Producto  120 non-null    object
 2   Categoria        120 non-null    object
 3   Subcategoria     120 non-null    object
 4   Precio_Lista     120 non-null    float64
 5   Costo_Unitario   120 non-null    float64
 6   Marca            120 non-null    object
 7   Activo           120 non-null    int64
 8   Codigo_Barra     120 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 8.6+ KB

In [ ]:
#visualizacion de las columnas de "Productos".
df_productos.head(2)

,ID_Producto,Nombre_Producto,Categoria,Subcategoria,Precio_Lista,Costo_Unitario,Marca,Activo,Codigo_Barra
0,P0001,Accesorios Flex 1,Tecnología,Accesorios,445.84,210.50,Alerce,1,7154379937124
1,P0002,Accesorios Smart 2,Tecnología,Accesorios,10.06,5.92,Vector,1,5756924593752

In [ ]:
#estadisticas de precios y costos. NO HAY NADA RARO
df_productos['Precio_Lista'].describe()

count    120.000000
mean     472.074000
std      261.208663
min       10.060000
25%      240.500000
50%      504.625000
75%      700.025000
max      891.670000
Name: Precio_Lista, dtype: float64

In [ ]:
print(df_productos['Categoria'].value_counts())

print(" ")
print(df_productos['Subcategoria'].value_counts())
print(" ")
print(df_productos['Marca'].value_counts())

Categoria
Tecnología    40
Muebles       40
Oficina       40
Name: count, dtype: int64

Subcategoria
Accesorios        10
Teléfonos         10
Computadores      10
Periféricos       10
Sillas            10
Mesas             10
Libreros          10
Almacenamiento    10
Papelería         10
Archivadores      10
Etiquetas         10
Sobres            10
Name: count, dtype: int64

Marca
Vector       18
Orion        18
Andes        18
Patagonia    17
Alerce       15
Altura       14
Lumen        14
Nova          6
Name: count, dtype: int64

In [ ]:
df_productos.describe(include = 'all')

,ID_Producto,Nombre_Producto,Categoria,Subcategoria,Precio_Lista,Costo_Unitario,Marca,Activo,Codigo_Barra
count,120,120,120,120,120.000000,120.000000,120,120.00000,120
unique,120,120,3,12,NaN,NaN,8,NaN,120
top,P0001,Accesorios Flex 1,Tecnología,Accesorios,NaN,NaN,Vector,NaN,7154379937124
freq,1,1,40,10,NaN,NaN,18,NaN,1
mean,NaN,NaN,NaN,NaN,472.074000,293.309667,NaN,0.97500,NaN
std,NaN,NaN,NaN,NaN,261.208663,171.846796,NaN,0.15678,NaN
min,NaN,NaN,NaN,NaN,10.060000,5.000000,NaN,0.00000,NaN
25%,NaN,NaN,NaN,NaN,240.500000,154.057500,NaN,1.00000,NaN
50%,NaN,NaN,NaN,NaN,504.625000,287.895000,NaN,1.00000,NaN
75%,NaN,NaN,NaN,NaN,700.025000,424.162500,NaN,1.00000,NaN
max,NaN,NaN,NaN,NaN,891.670000,692.480000,NaN,1.00000,NaN

#### Limpieza - Producto

In [ ]:
#verificacion de duplicados. NO HAY DUPLICADOS DE ID_Producto, NI DE CODIGO DE BARRAS
print(df_productos['Codigo_Barra'].duplicated().sum())
print('')
#condicion logica para detectar si hay algun precio de lista negativo.
df_limpio_preciolista = df_productos[df_productos['Precio_Lista'] < 0]
print(df_limpio_preciolista['Precio_Lista'].sum())
print('')
#condicion logica para detectar si hay algun costo unitario negativo.
df_limpio_costounitario = df_productos[df_productos['Costo_Unitario'] < 0]
print(df_limpio_costounitario['Costo_Unitario'].sum())
print('')
#verificamos si hay valores nulos. NO HAY VALORES NULOS EN NINGUNA COLUMNA
print(df_productos['Nombre_Producto'].isna().sum())
print('')
#verificamos que no haya ningun outlier de escritura en categoria y subcategoria. NO HAY NINGUNO
print(df_productos["Subcategoria"].value_counts())
print('')
#verificamos si no hay costos y precios menores a 0. NO LOS HAY.
(df_productos["Costo_Unitario"] <= 0).sum()

0

0.0

0.0

0

Subcategoria
Accesorios        10
Teléfonos         10
Computadores      10
Periféricos       10
Sillas            10
Mesas             10
Libreros          10
Almacenamiento    10
Papelería         10
Archivadores      10
Etiquetas         10
Sobres            10
Name: count, dtype: int64

np.int64(0)

## Joins de Tablas

In [ ]:
#Joins de las tablas de ubicacion
df_clientes_Ubi_1 = pd.merge(df_clientes, df_cli_ubicacion, on= 'ID_Cliente', how='left')

df_clientes_Ubi_Complete = pd.merge(df_clientes_Ubi_1, df_geografia, on = 'ID_Ubicacion', how= 'left')
df_clientes_Ubi_Complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           300 non-null    object
 1   Nombre_Cliente       300 non-null    object
 2   Segmento             300 non-null    object
 3   Fecha_Registro       300 non-null    datetime64[ns]
 4   Canal_Preferido      300 non-null    object
 5   Puntaje_Fidelidad    300 non-null    int64
 6   Codigo_Interno       300 non-null    object
 7   Antiguedad_Dias      300 non-null    int64
 8   ID_Ubicacion         300 non-null    object
 9   Tipo_Direccion       300 non-null    object
 10  Fecha_Actualizacion  300 non-null    datetime64[ns]
 11  Pais                 300 non-null    object
 12  Region               300 non-null    object
 13  Estado               300 non-null    object
 14  Ciudad               300 non-null    object
 15  Codigo_Postal        300 non-null    object
 16  Zona_Logistica       300 non-null    object
 17  Latitud_Ref          300 non-null    float64
dtypes: datetime64[ns](2), float64(1), int64(2), object(13)
memory usage: 42.3+ KB

In [ ]:
#Joins de las tablas de pedidos
df_pedidos_detPedidos = pd.merge(df_pedidos, df_det_pedidos, on= 'ID_Pedido', how= 'left' )

df_pedidos_Complete = pd.merge(df_pedidos_detPedidos, df_productos, on= 'ID_Producto', how= 'left')
df_pedidos_Complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3026 entries, 0 to 3025
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_Pedido              3026 non-null   object
 1   ID_Cliente             3026 non-null   object
 2   Fecha_Pedido           3026 non-null   datetime64[ns]
 3   Fecha_Envio            3026 non-null   datetime64[ns]
 4   Modo_Envio             3026 non-null   object
 5   ID_Campania            3026 non-null   object
 6   Estado_Pedido          3026 non-null   object
 7   Observacion_Interna    3026 non-null   object
 8   ID_Detalle             3026 non-null   int64
 9   ID_Producto            3026 non-null   object
 10  Cantidad               3026 non-null   int64
 11  Descuento              3026 non-null   float64
 12  Ventas                 3026 non-null   float64
 13  Ganancia               3026 non-null   float64
 14  Prioridad              3026 non-null   object
 15  Etiqueta_Ganancia      3026 non-null   object
 16  Etiqueta_Ventas        3026 non-null   object
 17  Margen_Rentabilidad_%  3026 non-null   float64
 18  Nombre_Producto        3026 non-null   object
 19  Categoria              3026 non-null   object
 20  Subcategoria           3026 non-null   object
 21  Precio_Lista           3026 non-null   float64
 22  Costo_Unitario         3026 non-null   float64
 23  Marca                  3026 non-null   object
 24  Activo                 3026 non-null   int64
 25  Codigo_Barra           3026 non-null   object
dtypes: datetime64[ns](2), float64(6), int64(3), object(15)
memory usage: 614.8+ KB

In [ ]:
#Join de la tabla final y verificacion
df_clientes_Final = pd.merge(df_pedidos_Complete, df_clientes_Ubi_Complete, on='ID_Cliente', how ='left')
df_clientes_Final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3026 entries, 0 to 3025
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_Pedido              3026 non-null   object
 1   ID_Cliente             3026 non-null   object
 2   Fecha_Pedido           3026 non-null   datetime64[ns]
 3   Fecha_Envio            3026 non-null   datetime64[ns]
 4   Modo_Envio             3026 non-null   object
 5   ID_Campania            3026 non-null   object
 6   Estado_Pedido          3026 non-null   object
 7   Observacion_Interna    3026 non-null   object
 8   ID_Detalle             3026 non-null   int64
 9   ID_Producto            3026 non-null   object
 10  Cantidad               3026 non-null   int64
 11  Descuento              3026 non-null   float64
 12  Ventas                 3026 non-null   float64
 13  Ganancia               3026 non-null   float64
 14  Prioridad              3026 non-null   object
 15  Etiqueta_Ganancia      3026 non-null   object
 16  Etiqueta_Ventas        3026 non-null   object
 17  Margen_Rentabilidad_%  3026 non-null   float64
 18  Nombre_Producto        3026 non-null   object
 19  Categoria              3026 non-null   object
 20  Subcategoria           3026 non-null   object
 21  Precio_Lista           3026 non-null   float64
 22  Costo_Unitario         3026 non-null   float64
 23  Marca                  3026 non-null   object
 24  Activo                 3026 non-null   int64
 25  Codigo_Barra           3026 non-null   object
 26  Nombre_Cliente         3026 non-null   object
 27  Segmento               3026 non-null   object
 28  Fecha_Registro         3026 non-null   datetime64[ns]
 29  Canal_Preferido        3026 non-null   object
 30  Puntaje_Fidelidad      3026 non-null   int64
 31  Codigo_Interno         3026 non-null   object
 32  Antiguedad_Dias        3026 non-null   int64
 33  ID_Ubicacion           3026 non-null   object
 34  Tipo_Direccion         3026 non-null   object
 35  Fecha_Actualizacion    3026 non-null   datetime64[ns]
 36  Pais                   3026 non-null   object
 37  Region                 3026 non-null   object
 38  Estado                 3026 non-null   object
 39  Ciudad                 3026 non-null   object
 40  Codigo_Postal          3026 non-null   object
 41  Zona_Logistica         3026 non-null   object
 42  Latitud_Ref            3026 non-null   float64
dtypes: datetime64[ns](4), float64(7), int64(5), object(27)
memory usage: 1016.7+ KB

In [ ]:
#Limpieza de clientes Final
df_clientes_Final = df_clientes_Final.drop(columns=['ID_Campania', 'ID_Producto','ID_Detalle',
                                                    'Precio_Lista','Costo_Unitario','Codigo_Barra','Codigo_Interno','Ciudad',
                                                    'ID_Ubicacion','Codigo_Postal','Zona_Logistica', 'Tipo_Direccion',
                                                    'Pais','Descuento', 'Fecha_Envio','Activo','Latitud_Ref','Observacion_Interna'])

In [ ]:
df_clientes_Final = df_clientes_Final[[ 'ID_Cliente','Nombre_Cliente','Fecha_Registro','Antiguedad_Dias','Segmento',
                                       'Puntaje_Fidelidad','Canal_Preferido','Region','Estado','Fecha_Actualizacion','ID_Pedido',
                                       'Fecha_Pedido','Modo_Envio','Prioridad','Estado_Pedido','Ventas','Etiqueta_Ventas','Ganancia','Etiqueta_Ganancia',
                                       'Margen_Rentabilidad_%','Nombre_Producto','Cantidad','Categoria','Subcategoria','Marca'
                                       ]]

In [ ]:
df_clientes_Final['Antiguedad_Dias'] = (df_clientes_Final['Fecha_Pedido'] - df_clientes_Final['Fecha_Registro']).dt.days

In [ ]:
df_clientes_Final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3026 entries, 0 to 3025
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_Cliente             3026 non-null   object
 1   Nombre_Cliente         3026 non-null   object
 2   Fecha_Registro         3026 non-null   datetime64[ns]
 3   Antiguedad_Dias        3026 non-null   int64
 4   Segmento               3026 non-null   object
 5   Puntaje_Fidelidad      3026 non-null   int64
 6   Canal_Preferido        3026 non-null   object
 7   Region                 3026 non-null   object
 8   Estado                 3026 non-null   object
 9   Fecha_Actualizacion    3026 non-null   datetime64[ns]
 10  ID_Pedido              3026 non-null   object
 11  Fecha_Pedido           3026 non-null   datetime64[ns]
 12  Modo_Envio             3026 non-null   object
 13  Prioridad              3026 non-null   object
 14  Estado_Pedido          3026 non-null   object
 15  Ventas                 3026 non-null   float64
 16  Etiqueta_Ventas        3026 non-null   object
 17  Ganancia               3026 non-null   float64
 18  Etiqueta_Ganancia      3026 non-null   object
 19  Margen_Rentabilidad_%  3026 non-null   float64
 20  Nombre_Producto        3026 non-null   object
 21  Cantidad               3026 non-null   int64
 22  Categoria              3026 non-null   object
 23  Subcategoria           3026 non-null   object
 24  Marca                  3026 non-null   object
dtypes: datetime64[ns](3), float64(3), int64(3), object(16)
memory usage: 591.1+ KB

In [ ]:
display(df_clientes_Final.head())

,ID_Cliente,Nombre_Cliente,Fecha_Registro,Antiguedad_Dias,Segmento,Puntaje_Fidelidad,Canal_Preferido,Region,Estado,Fecha_Actualizacion,...,Ventas,Etiqueta_Ventas,Ganancia,Etiqueta_Ganancia,Margen_Rentabilidad_%,Nombre_Producto,Cantidad,Categoria,Subcategoria,Marca
0,C0174,Nicolás Martínez,2021-11-09,1238,Corporativo,18,Correo,Sur,Los Lagos,2024-12-26,...,590.86,Normal,322.42,Normal,54.57,Papelería Eco 2,1,Oficina,Papelería,Orion
1,C0174,Nicolás Martínez,2021-11-09,1238,Corporativo,18,Correo,Sur,Los Lagos,2024-12-26,...,4341.68,Normal,1907.85,Normal,43.94,Sobres Plus 9,7,Oficina,Sobres,Andes
2,C0174,Nicolás Martínez,2021-11-09,1238,Corporativo,18,Correo,Sur,Los Lagos,2024-12-26,...,1250.86,Normal,281.32,Normal,22.49,Sillas Plus 8,2,Muebles,Sillas,Orion
3,C0174,Nicolás Martínez,2021-11-09,1238,Corporativo,18,Correo,Sur,Los Lagos,2024-12-26,...,244.35,Normal,64.85,Normal,26.54,Almacenamiento Nova 9,5,Muebles,Almacenamiento,Alerce
4,C0254,Isidora Rojas,2022-09-26,546,Consumidor,71,Correo,Sur,Biobío,2024-01-29,...,629.31,Normal,115.33,Normal,18.33,Papelería Flex 7,1,Oficina,Papelería,Andes

## Conversion a CSV

In [ ]:
df_clientes_Final.to_csv('Dataset_Clientes_Final.csv', index= False)