In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')
"""
Esto es para usar tu cuenta de drive, esto es personal para cada uno por lo que
no se expondra informacion personal. Deberas darle permisos a Colab para acceder
a tu google drive

Para que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu
drive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro
el archivo de 34_SuperTienda_Espanol.db

Mas abajo dejare una opcion para ejecutarlo sin el drive.
"""

'\nEsto es para usar tu cuenta de drive, esto es personal para cada uno por lo que\nno se expondra informacion personal. Deberas darle permisos a Colab para acceder\na tu google drive\n\nPara que se ejecute bien, debes crear en tu drive las siguientes carpetas en tu\ndrive: Hitos_Skillnest, dentro de ella crear la carpeta Hito1 y colocar dentro\nel archivo de 34_SuperTienda_Espanol.db\n\nMas abajo dejare una opcion para ejecutarlo sin el drive.\n'

In [ ]:
#Setting de sql y pandas
import sqlite3
import pandas as pd

%load_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

"""
Dependiendo de la opcion que uses, deberas comentar una opcion u otra para
evitar generar errores y luego cambiarlo en conn = sqlite3.connect(opcion_Elegida)
"""

#Ruta del archivo guardada en drive
#ruta_drive = '/content/drive/MyDrive/Hitos_Skillnest/Hito1/34_SuperTienda_Espanol.db'

#Ruta del archivo subida al entorno, debes subirlo a la raiz del entorno de ejecucion.
ruta = '/content/34_SuperTienda_Espanol.db'

"""
-----------------------------------------------
"""

#Cambiar la variable de ruta segun si estas usando el drive o el archivo subido
#al entorno de ejecucion
conn = sqlite3.connect(ruta) #Se realiza la conexion con la base de datos


#Guardamos la consulta SQL como string, en este caso es para poder conseguir
# el nombre de las tablas presentes en la base de datos.
query = "SELECT name FROM sqlite_master WHERE type='table';"

#ejecutamos la consulta en la base de datos
df_tables =  pd.read_sql_query(query, conn)

print(df_tables) # :D tablas

                name
0           Clientes
1          Productos
2          Geografia
3  Cliente_Ubicacion
4          Campanias
5            Pedidos
6     Detalle_Pedido
7            Soporte

In [ ]:
#Setting de los Dataframes

df_clientes = pd.read_sql("SELECT * FROM Clientes", conn)

df_productos = pd.read_sql("SELECT * FROM Productos", conn)

df_geografia = pd.read_sql("SELECT * FROM Geografia", conn)

df_cli_ubicacion = pd.read_sql("SELECT * FROM Cliente_Ubicacion", conn)

df_camp = pd.read_sql("SELECT * FROM Campanias", conn)

df_pedidos = pd.read_sql("SELECT * FROM Pedidos", conn)

df_det_pedidos = pd.read_sql("SELECT * FROM Detalle_Pedido", conn)

df_soporte = pd.read_sql("SELECT * FROM Soporte", conn)

Enfoque de clientes

Variables a calcular:

Cuales son los segmentos que mas pedidos realizan, Cuales son las categorias mas pedidas por cada segmento, cuales son los segmentos que producen mayor inversion, los canales preferidos mas utilizados en general, los canales preferidos mas utilizado por cada segmento, la media del puntaje de fidelidad, posible relacion entre segmentos y puntos de fidelidad.

In [ ]:
df_clientes

,ID_Cliente,Nombre_Cliente,Segmento,Fecha_Registro,Canal_Preferido,Puntaje_Fidelidad,Codigo_Interno
0,C0001,Fernanda Díaz,Consumidor,2023-02-18,Web,55,CLI-6635-Z
1,C0002,Valentina Muñoz,Home Office,2023-07-30,Web,58,CLI-2291-Z
2,C0003,Diego Castillo,Corporativo,2024-03-28,App,100,CLI-2139-X
3,C0004,Nicolás Silva,Corporativo,2021-06-13,App,22,CLI-7227-Y
4,C0005,Daniela Rodríguez,Consumidor,2023-01-29,Teléfono,36,CLI-5374-Z
...,...,...,...,...,...,...,...
295,C0296,Catalina Muñoz,Consumidor,2024-08-28,App,78,CLI-1611-X
296,C0297,Sebastián Soto,Consumidor,2023-03-25,Correo,33,CLI-5742-X
297,C0298,Ana Sepúlveda,Home Office,2024-05-19,Web,52,CLI-5662-Y
298,C0299,Catalina Flores,Home Office,2023-10-09,App,74,CLI-8668-Y
299,C0300,Camila Díaz,Corporativo,2021-11-29,Correo,92,CLI-5215-Z

In [ ]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_Cliente         300 non-null    object
 1   Nombre_Cliente     300 non-null    object
 2   Segmento           300 non-null    object
 3   Fecha_Registro     300 non-null    object
 4   Canal_Preferido    283 non-null    object
 5   Puntaje_Fidelidad  300 non-null    int64
 6   Codigo_Interno     300 non-null    object
dtypes: int64(1), object(6)
memory usage: 16.5+ KB

In [ ]:
df_clientes.isnull().sum()

ID_Cliente            0
Nombre_Cliente        0
Segmento              0
Fecha_Registro        0
Canal_Preferido      17
Puntaje_Fidelidad     0
Codigo_Interno        0
dtype: int64

In [ ]:
df_clientes.describe()

       Puntaje_Fidelidad
count         300.000000
mean           57.143333
std            25.982168
min            10.000000
25%            38.000000
50%            56.000000
75%            80.000000
max           100.000000

In [ ]:
# Verificación y conversión de tipos de datos
df_clientes['Fecha_Registro'] = pd.to_datetime(df_clientes['Fecha_Registro'])

In [ ]:
# Tratamiento de Valores Nulos
# Reemplazamos los canales preferidos faltantes por 'No Especificado'
df_clientes['Canal_Preferido'] = df_clientes['Canal_Preferido'].fillna('No Especificado')

In [ ]:
# Eliminar duplicados
df_clientes = df_clientes.drop_duplicates()

In [ ]:
# Limpiar espacios en blanco
columnas_texto = ["Nombre_Cliente","Segmento","Canal_Preferido"]
for col in columnas_texto:
    df_clientes[col] = df_clientes[col].str.strip()

In [ ]:
df_clientes["Puntaje_Fidelidad"].describe()

count    300.000000
mean      57.143333
std       25.982168
min       10.000000
25%       38.000000
50%       56.000000
75%       80.000000
max      100.000000
Name: Puntaje_Fidelidad, dtype: float64

In [ ]:
# Formato consistente
df_clientes["Canal_Preferido"] = df_clientes["Canal_Preferido"].str.title()

In [ ]:
# Variable tiempo
fecha_actual = pd.Timestamp.today()

df_clientes["Antiguedad_Dias"] = (
    fecha_actual - df_clientes["Fecha_Registro"]
).dt.days

In [ ]:
# Verificación final
print(df_clientes.isnull().sum())
print(df_clientes.duplicated().sum())

df_clientes.head()

ID_Cliente           0
Nombre_Cliente       0
Segmento             0
Fecha_Registro       0
Canal_Preferido      0
Puntaje_Fidelidad    0
Codigo_Interno       0
Antiguedad_Dias      0
dtype: int64
0

,ID_Cliente,Nombre_Cliente,Segmento,Fecha_Registro,Canal_Preferido,Puntaje_Fidelidad,Codigo_Interno,Antiguedad_Dias
0,C0001,Fernanda Díaz,Consumidor,2023-02-18,Web,55,CLI-6635-Z,1238
1,C0002,Valentina Muñoz,Home Office,2023-07-30,Web,58,CLI-2291-Z,1076
2,C0003,Diego Castillo,Corporativo,2024-03-28,App,100,CLI-2139-X,834
3,C0004,Nicolás Silva,Corporativo,2021-06-13,App,22,CLI-7227-Y,1853
4,C0005,Daniela Rodríguez,Consumidor,2023-01-29,Teléfono,36,CLI-5374-Z,1258

In [ ]:
df_clientes.describe(include="all")

,ID_Cliente,Nombre_Cliente,Segmento,Fecha_Registro,Canal_Preferido,Puntaje_Fidelidad,Codigo_Interno,Antiguedad_Dias
count,300,300,300,300,300,300.000000,300,300.000000
unique,300,231,3,NaN,5,NaN,300,NaN
top,C0300,Fernanda Díaz,Corporativo,NaN,Web,NaN,CLI-5215-Z,NaN
freq,1,4,106,NaN,81,NaN,1,NaN
mean,NaN,NaN,NaN,2023-02-02 05:12:00,NaN,57.143333,NaN,1253.783333
min,NaN,NaN,NaN,2021-01-17 00:00:00,NaN,10.000000,NaN,617.000000
25%,NaN,NaN,NaN,2022-03-27 12:00:00,NaN,38.000000,NaN,929.750000
50%,NaN,NaN,NaN,2023-02-20 00:00:00,NaN,56.000000,NaN,1236.000000
75%,NaN,NaN,NaN,2023-12-23 06:00:00,NaN,80.000000,NaN,1565.500000
max,NaN,NaN,NaN,2024-10-31 00:00:00,NaN,100.000000,NaN,2000.000000
std,NaN,NaN,NaN,NaN,NaN,25.982168,NaN,389.558188